version: '3'
services:
  app:
    build: .
    container_name: challenge-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/challenge/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: innovea-challenge-db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
